# -*- coding: utf-8 -*-
"""FULL INTEGRATED FLOOD ANALYSIS PIPELINE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Om23qKj6aay6gll5EUbpDdoV3_D55vyz
"""

# ============================================================
# FULL INTEGRATED FLOOD ANALYSIS PIPELINE
# ============================================================

import rasterio
import geopandas as gpd
import numpy as np
from rasterio.features import shapes, rasterize
from shapely.geometry import shape
from rasterstats import zonal_stats
from rasterio.warp import reproject, Resampling, calculate_default_transform

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------
dem = r"/content/drive/MyDrive/Bengaluru_Floods/Dem_Carto.tif"
floodpixel = r"/content/drive/MyDrive/Bengaluru_Floods/Flood_Pixel.tif"
imper = r"/content/drive/MyDrive/Bengaluru_Floods/Impervious.tif"

# ============================================================
# 1️⃣ VECTORIZE FLOOD PIXEL RASTER
# ============================================================

print("\nSTEP 1: Raster → Vector...")

with rasterio.open(floodpixel) as src:
    band = src.read(1)
    transform = src.transform
    nodata = src.nodata

mask = band != nodata

polygons, values = [], []

for geom, val in shapes(band, mask=mask, transform=transform):
    polygons.append(shape(geom))
    values.append(val)

gdf = gpd.GeoDataFrame({"maximum": values}, geometry=polygons, crs=src.crs)
gdf.to_file("Floodvectorized.shp", driver="ESRI Shapefile")

print("✔ Vectorization saved → Floodvectorized.shp")


# ============================================================
# 2️⃣ ZONAL MAX USING DEM
# ============================================================

print("\nSTEP 2: Zonal Max...")

stats = zonal_stats(
    "Floodvectorized.shp",
    dem,
    stats=["max"],
    nodata=None
)

gdf["max_value"] = [s["max"] for s in stats]
gdf.to_file("zonal_max.shp")

print("✔ Zonal max saved → zonal_max.shp")


# ============================================================
# 3️⃣ RASTERIZE MAX VALUES TO DEM GRID
# ============================================================

print("\nSTEP 3: Rasterizing max values...")

gdf2 = gpd.read_file("zonal_max.shp")

with rasterio.open(dem) as src:
    meta = src.meta.copy()
    transform = src.transform
    out_shape = (src.height, src.width)

shps = [(geom, val) for geom, val in zip(gdf2.geometry, gdf2.max_value)]

rasterized = rasterize(
    shps,
    out_shape=out_shape,
    transform=transform,
    fill=0,
    dtype=meta["dtype"]
)

meta.update(count=1)
with rasterio.open("dem_max.tif", "w", **meta) as dst:
    dst.write(rasterized, 1)

print("✔ DEM max raster saved → dem_max.tif")


# ============================================================
# 4️⃣ FLOOD DEPTH = DEM - DEM_MAX (masked)
# ============================================================

print("\nSTEP 4: Flood depth calculation...")

max_ras = "dem_max.tif"
mask_ras = floodpixel
other_ras = dem

# Reference raster
with rasterio.open(max_ras) as src_ref:
    max_arr = src_ref.read(1)
    ref_meta = src_ref.meta.copy()
    ref_transform = src_ref.transform
    ref_crs = src_ref.crs
    ref_shape = max_arr.shape

# Resample other_ras to reference
def resample_to_ref(src_path, ref_shape, ref_transform, ref_crs, method=Resampling.bilinear):
    with rasterio.open(src_path) as src:
        arr0 = src.read(1)
        arr = np.zeros(ref_shape, dtype=src.meta['dtype'])
        reproject(
            arr0, arr,
            src_transform=src.transform,
            src_crs=src.crs,
            dst_transform=ref_transform,
            dst_crs=ref_crs,
            resampling=method
        )
        return arr

other_arr = resample_to_ref(other_ras, ref_shape, ref_transform, ref_crs)
mask_arr = resample_to_ref(mask_ras, ref_shape, ref_transform, ref_crs, Resampling.nearest)

valid_mask = mask_arr > 0

result = np.zeros(ref_shape, dtype=np.float32)
result[valid_mask] = other_arr[valid_mask] - max_arr[valid_mask]

ref_meta.update(dtype="float32")
with rasterio.open("flood_depth.tif", "w", **ref_meta) as dst:
    dst.write(result, 1)

print("✔ Flood depth raster saved → flood_depth.tif")


# ============================================================
# 5️⃣ FLOOD VOLUME CALCULATION (Impervious & Pervious)
# ============================================================

print("\nSTEP 5: Flood volume calculation...")

value_raster = "flood_depth.tif"
imper_raster = imper
reference_mask_raster = value_raster
dst_crs = "EPSG:32643"

# Reproject value raster to projected CRS
with rasterio.open(value_raster) as src:
    transform, width, height = calculate_default_transform(
        src.crs, dst_crs, src.width, src.height, *src.bounds
    )
    meta = src.meta.copy()
    meta.update(crs=dst_crs, transform=transform, width=width, height=height)

    val_arr = np.zeros((height, width), dtype=src.meta['dtype'])
    reproject(
        source=rasterio.band(src, 1), destination=val_arr,
        src_transform=src.transform, src_crs=src.crs,
        dst_transform=transform, dst_crs=dst_crs,
        resampling=Resampling.bilinear
    )

def align(src_path):
    with rasterio.open(src_path) as src:
        out = np.zeros(val_arr.shape, dtype=src.meta['dtype'])
        reproject(
            rasterio.band(src, 1), out,
            src_transform=src.transform, src_crs=src.crs,
            dst_transform=transform, dst_crs=dst_crs,
            resampling=Resampling.nearest
        )
        return out

imp_arr = align(imper_raster)
ref_arr = align(reference_mask_raster)

pixel_w = transform[0]
pixel_h = -transform[4]
cell_area = pixel_w * pixel_h

print("Cell Area (m²):", cell_area)

impervious_mask = (imp_arr == 1) & (ref_arr != 0)
pervious_mask = (imp_arr == 0) & (ref_arr != 0)

vol_impervious = float(np.sum(val_arr[impervious_mask] * cell_area))
vol_pervious = float(np.sum(val_arr[pervious_mask] * cell_area))

print("\n=========== VOLUME RESULTS ===========")
print(f"Impervious Volume (m³): {vol_impervious:,.2f}")
print(f"Pervious Volume   (m³): {vol_pervious:,.2f}")
print("======================================")

